import { Component, OnInit } from '@angular/core';
import { ModalController, LoadingController, AlertController } from '@ionic/angular';
import { AngularFirestore } from '@angular/fire/firestore';

@Component({
  selector: 'app-editareas',
  templateUrl: './editareas.page.html',
  styleUrls: ['./editareas.page.scss'],
})
export class EditareasPage implements OnInit {
area;
pid;
Areasegment="am"
  constructor(
    private modalController: ModalController,
    private afs : AngularFirestore,
    private loadingController: LoadingController,
    private alertController: AlertController
    ) { }

  ngOnInit() {
  }
  close(){
   this.modalController.dismiss()
  }

  async update(){
       const loading = await this.loadingController.create({
         message: 'Updating...',
         duration: 20000,
         spinner: 'bubbles'
       });
       await loading.present();
       this.afs.doc(`boq/boq/projects/${this.pid}/buildings/${this.area.BuildingID}/floors/${this.area.floorID}/cat/${this.area.catid}/subcat/${this.area.subcatid}/subsubcat/${this.area.subsubcatid}/areas/${this.area.id}`).update({
        catname : this.area.catname,
        catid :  this.area.catid,
        subcatname : this.area.subcatname,
        subcatid : this.area.subcatid,
        subsubcatname : this.area.subsubcatname,
        subsubcatid : this.area.subsubcatid,
        name : this.area.name,
        floorname : this.area.floorname,
        floorID : this.area.floorID,
        BuildingID : this.area.BuildingID,
        Unit_width : this.area.Unit_width,
        Unit_length : this.area.Unit_length,
        Unit_height : this.area.Unit_height,
        No_of_units : this.area.No_of_units,
        R : this.area.R,
        RO : this.area.RO,
        L1 : this.area.L1,
        L2 : this.area.L2,
        L3 : this.area.L3,
        L4 : this.area.L4,
        L5 : this.area.L5,
        L6 : this.area.L6,
        L7 : this.area.L7,
        L8 : this.area.L8,
        Hal_Axis : this.area.Hal_Axis,
        Val_Axis : this.area.Val_Axis,
        Floor_width_1 : this.area.Floor_width_1,
        Floor_width_2 : this.area.Floor_width_2,
        Floor_width_3 : this.area.Floor_width_3,
        Floor_width_4 : this.area.Floor_width_4,
        Floor_length_1 : this.area.Floor_length_1,
        Floor_length_2 : this.area.Floor_length_2,
        Floor_length_3 : this.area.Floor_length_3,
        Floor_length_4 : this.area.Floor_length_4,
        Wall_per_lengthA : this.area.Wall_per_lengthA,
        Wall_per_lengthB : this.area.Wall_per_lengthB,
        Wall_per_lengthC : this.area.Wall_per_lengthC,
        Wall_per_lengthD : this.area.Wall_per_lengthD,
        Wall_per_lengthE : this.area.Wall_per_lengthE,
        Wall_per_lengthF : this.area.Wall_per_lengthF,
        Wall_per_lengthG : this.area.Wall_per_lengthG,
        Wall_per_lengthH : this.area.Wall_per_lengthH,
        skirting_per_lengthA : this.area.skirting_per_lengthA,
        skirting_per_lengthB : this.area.skirting_per_lengthB,
        skirting_per_lengthC : this.area.skirting_per_lengthC,
        skirting_per_lengthD : this.area.skirting_per_lengthD,
        skirting_per_lengthE : this.area.skirting_per_lengthE,
        skirting_per_lengthF : this.area.skirting_per_lengthF,
        skirting_per_lengthG : this.area.skirting_per_lengthG,
        skirting_per_lengthH : this.area.skirting_per_lengthH,
        PCLA : this.area.PCLA,
        PCLB : this.area.PCLB,
        PCLC : this.area.PCLC,
        PCLD : this.area.PCLD,
        PCLE : this.area.PCLE,
        PCLF : this.area.PCLF,
        PCLG : this.area.PCLG,
        PCLH : this.area.PCLH,
        Y8 : this.area.Y8,
        Y10 : this.area.Y10,
        Y12 : this.area.Y12,
        Y16 : this.area.Y16,
        Y20 : this.area.Y20,
        Y25 : this.area.Y25,
        Y32 : this.area.Y32,
        Y14 : this.area.Y14,
        Y6 : this.area.Y6,
        Y18 : this.area.Y18,
        Y22 : this.area.Y22,
        Y28 : this.area.Y28,
        Y40 : this.area.Y40,
        areaF : this.area.areaF,
        areaW : this.area.areaW,
        areaC : this.area.areaC,
        areaS : this.area.areaS,
        areaCOR : this.area.areaCOR,
        areaB : this.area.areaB,
        extraBlockDPC : this.area.extraBlockDPC,
        conc : this.area.conc,
        shutt : this.area.shutt,
        bit : this.area.bit,
        polyth : this.area.polyth,
        steel : this.area.steel,
        exc : this.area.exc,
        fill : this.area.fill,
        precast : this.area.precast,
        EXTRAEXP : this.area.EXTRAEXP,
        EXTRACONCBO : this.area.EXTRACONCBO,
        EXTRACONCB : this.area.EXTRACONCB,


ch1A : this.area.ch1A,
ch1B : this.area.ch1B,
ch1C : this.area.ch1C,
ch1D : this.area.ch1D,
ch1E : this.area.ch1E,
ch1F : this.area.ch1F,
ch1G : this.area.ch1G,
ch1H : this.area.ch1H,
ch1I : this.area.ch1I,
ch1J : this.area.ch1J,
ch1K : this.area.ch1K,
ch1L : this.area.ch1L,
ch1M : this.area.ch1M,
ch1N : this.area.ch1N,
ch1O : this.area.ch1O,
ch1P : this.area.ch1P,
ch1Q : this.area.ch1Q,
ch1R : this.area.ch1R,
ch1S : this.area.ch1S,
ch1T : this.area.ch1T,
ch1U : this.area.ch1U,
ch1V : this.area.ch1V,
ch1W : this.area.ch1W,
ch1X : this.area.ch1X,
ch1Y : this.area.ch1Y,
ch1Z : this.area.ch1Z,
ch1AA : this.area.ch1AA,
ch1AB : this.area.ch1AB,
ch1AC : this.area.ch1AC,
ch1AD : this.area.ch1AD,
ch1AE : this.area.ch1AE,
ch1AF : this.area.ch1AF,
ch1AG : this.area.ch1AG,
ch1AH : this.area.ch1AH,
ch1AI : this.area.ch1AI,
ch1AJ : this.area.ch1AJ,
ch1AK : this.area.ch1AK,
ch1AL : this.area.ch1AL,
ch1AM : this.area.ch1AM,
ch1AN : this.area.ch1AN,
ch1AO : this.area.ch1AO,

ch2A : this.area.ch2A,
ch2B : this.area.ch2B,
ch2C : this.area.ch2C,
ch2D : this.area.ch2D,
ch2E : this.area.ch2E,
ch2F : this.area.ch2F,
ch2G : this.area.ch2G,
ch2H : this.area.ch2H,
ch2I : this.area.ch2I,
ch2J : this.area.ch2J,
ch2K : this.area.ch2K,
ch2L : this.area.ch2L,
ch2M : this.area.ch2M,
ch2N : this.area.ch2N,
ch2O : this.area.ch2O,
ch2P : this.area.ch2P,
ch2Q : this.area.ch2Q,
ch2R : this.area.ch2R,
ch2S : this.area.ch2S,
ch2T : this.area.ch2T,
ch2U : this.area.ch2U,
ch2V : this.area.ch2V,
ch2W : this.area.ch2W,
ch2X : this.area.ch2X,
ch2Y : this.area.ch2Y,
ch2Z : this.area.ch2Z,
ch2AA : this.area.ch2AA,
ch2AB : this.area.ch2AB,
ch2AC : this.area.ch2AC,
ch2AD : this.area.ch2AD,
ch2AE : this.area.ch2AE,
ch2AF : this.area.ch2AF,
ch2AG : this.area.ch2AG,
ch2AH : this.area.ch2AH,
ch2AI : this.area.ch2AI,
ch2AJ : this.area.ch2AJ,
ch2AK : this.area.ch2AK,
ch2AL : this.area.ch2AL,
ch2AM : this.area.ch2AM,
ch2AN : this.area.ch2AN,
ch2AO : this.area.ch2AO,

ch3A : this.area.ch3A,
ch3B : this.area.ch3B,
ch3C : this.area.ch3C,
ch3D : this.area.ch3D,
ch3E : this.area.ch3E,
ch3F : this.area.ch3F,
ch3G : this.area.ch3G,
ch3H : this.area.ch3H,
ch3I : this.area.ch3I,
ch3J : this.area.ch3J,
ch3K : this.area.ch3K,
ch3L : this.area.ch3L,
ch3M : this.area.ch3M,
ch3N : this.area.ch3N,
ch3O : this.area.ch3O,
ch3P : this.area.ch3P,
ch3Q : this.area.ch3Q,
ch3R : this.area.ch3R,
ch3S : this.area.ch3S,
ch3T : this.area.ch3T,
ch3U : this.area.ch3U,
ch3V : this.area.ch3V,
ch3W : this.area.ch3W,
ch3X : this.area.ch3X,
ch3Y : this.area.ch3Y,
ch3Z : this.area.ch3Z,
ch3AA : this.area.ch3AA,
ch3AB : this.area.ch3AB,
ch3AC : this.area.ch3AC,
ch3AD : this.area.ch3AD,
ch3AE : this.area.ch3AE,
ch3AF : this.area.ch3AF,
ch3AG : this.area.ch3AG,
ch3AH : this.area.ch3AH,
ch3AI : this.area.ch3AI,
ch3AJ : this.area.ch3AJ,
ch3AK : this.area.ch3AK,
ch3AL : this.area.ch3AL,
ch3AM : this.area.ch3AM,
ch3AN : this.area.ch3AN,
ch3AO : this.area.ch3AO,
    
      }).then(()=>{
        loading.dismiss().then(()=>{
         alert("Upadted Successfully!")
        })
  })
}

}
